### ISSUE TITLE
Code Buggy

### ISSUE THREAD

**Issue by oniGino** [f5devcentral/f5-aws-migrate#3]
```
____CHECKING for UCS...
No CVE
RUNNING cmd: save /sys ucs /var/tmp/f5-i-07ffc6eceda783e06.ucs
cmd_output:
Saving active configuration...
/var/tmp/f5-i-07ffc6eceda783e06.ucs is saved.

RUNNING cmd: run util bash -c 'cp /var/tmp/f5-i-07ffc6eceda783e06.ucs /var/local/ucs'
cmd_output:

RUNNING cmd: run util bash -c 'md5sum /var/local/ucs/f5-i-07ffc6eceda783e06.ucs > /var/local/ucs/f5-i-07ffc6eceda783e06.ucs.md5'
cmd_output:

Downloading file: /var/tmp/f5-i-07ffc6eceda783e06.ucs from host: 10.15.10.57
scp_output:
None
Downloading file: /var/local/ucs/f5-i-07ffc6eceda783e06.ucs.md5 from host: 10.15.10.57
scp_output:
None

_____CHECKING AWS details for source BIG-IP...
Number of ENIs detected = 3
Processing DeviceIndex 1
Processing DeviceIndex 2
Processing DeviceIndex 0
Instance status is running
Terminating Instance Id: i-07ffc6eceda783e06...
Traceback (most recent call last):
  File "./f5-aws-migrate.py", line 1092, in <module>
    main()
  File "./f5-aws-migrate.py", line 815, in main
    instance_status = response['TerminatingInstances'][0]['CurrentState']['Name']
KeyError: 'TerminatingInstances'
exit status 1
```

Really concerned as this code is now 5+years old and hasn't been updated, also the above error happened on my attempt to use this

**Comment by oniGino** [comment]
termination protection was on,

would be nice to see those code ported to python3.x though
